{
 "title": "Prediction metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Пиковая нагрузка процессора",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(rate(process_cpu_seconds_total[1m])[5m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время метода предсказаний \"/predict\"",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Общее количество запросов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "prediction_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Медианное предсказанное значение",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, prediction_values_histogram_bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}